language: node_js

node_js:
  - '12.13'

script:
  - yarn lint
  - yarn test
  - yarn build
  - yarn coveralls

deploy:
  edge: true
  skip_cleanup: true
  provider: npm
  email: lee@😬.kz
  api_key:
    secure: 
  on:
    tags: true
    repo: tigwyk/accept-banano-client
